export const authConstants = {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_FAILURE:'LOGOUT_FAILURE',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS'
}

export const userConstant = {
    USER_REGISTER_REQUEST:'USER_REGISTER_REQUEST', 
    USER_REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE:'USER_REGISTER_FAILURE'
}

export const categoryConstant = {
    GET_ALL_CATEGORIES_REQUEST:'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS:'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE:'GET_ALL_CATEGORIES_FAILURE',
    ADD_NEW_CATEGORIES_REQUEST:'ADD_NEW_CATEGORIES_REQUEST',
    ADD_NEW_CATEGORIES_SUCCESS:'ADD_NEW_CATEGORIES_SUCCESS',
    ADD_NEW_CATEGORIES_FAILURE:'ADD_NEW_CATEGORIES_FAILURE',
}